const sectorMap = {
  ADANIENT:    { sector: 'Infrastructure',  fullName: 'Adani Enterprises' },
  ADANIPORTS:  { sector: 'Infrastructure',  fullName: 'Adani Ports' },
  APOLLOHOSP:  { sector: 'Healthcare',      fullName: 'Apollo Hospitals' },
  ASIANPAINT:  { sector: 'Consumer Goods',  fullName: 'Asian Paints' },
  AXISBANK:    { sector: 'Banking',         fullName: 'Axis Bank' },
  BAJAJ_AUTO:  { sector: 'Automobile',      fullName: 'Bajaj Auto' },
  BAJAJFINSV:  { sector: 'Financial',       fullName: 'Bajaj Finserv' },
  BAJFINANCE:  { sector: 'Financial',       fullName: 'Bajaj Finance' },
  BHARTIARTL:  { sector: 'Telecom',         fullName: 'Bharti Airtel' },
  BPCL:        { sector: 'Oil & Gas',       fullName: 'BPCL' },
  BRITANNIA:   { sector: 'Consumer Goods',  fullName: 'Britannia' },
  CIPLA:       { sector: 'Healthcare',      fullName: 'Cipla' },
  COALINDIA:   { sector: 'Mining',          fullName: 'Coal India' },
  DIVISLAB:    { sector: 'Healthcare',      fullName: 'Divis Laboratories' },
  DRREDDY:     { sector: 'Healthcare',      fullName: "Dr. Reddy's" },
  EICHERMOT:   { sector: 'Automobile',      fullName: 'Eicher Motors' },
  GRASIM:      { sector: 'Manufacturing',   fullName: 'Grasim Industries' },
  HCLTECH:     { sector: 'IT',              fullName: 'HCL Technologies' },
  HDFC:        { sector: 'Financial',       fullName: 'HDFC' },
  HDFCBANK:    { sector: 'Banking',         fullName: 'HDFC Bank' },
  HDFCLIFE:    { sector: 'Insurance',       fullName: 'HDFC Life' },
  HEROMOTOCO:  { sector: 'Automobile',      fullName: 'Hero MotoCorp' },
  HINDALCO:    { sector: 'Metals',          fullName: 'Hindalco' },
  HINDUNILVR:  { sector: 'Consumer Goods',  fullName: 'Hindustan Unilever' },
  ICICIBANK:   { sector: 'Banking',         fullName: 'ICICI Bank' },
  INDUSINDBK:  { sector: 'Banking',         fullName: 'IndusInd Bank' },
  INFY:        { sector: 'IT',              fullName: 'Infosys' },
  ITC:         { sector: 'Consumer Goods',  fullName: 'ITC' },
  JSWSTEEL:    { sector: 'Metals',          fullName: 'JSW Steel' },
  KOTAKBANK:   { sector: 'Banking',         fullName: 'Kotak Mahindra Bank' },
  LT:          { sector: 'Infrastructure',  fullName: 'Larsen & Toubro' },
  M_M:         { sector: 'Automobile',      fullName: 'Mahindra & Mahindra' },
  MARUTI:      { sector: 'Automobile',      fullName: 'Maruti Suzuki' },
  NESTLEIND:   { sector: 'Consumer Goods',  fullName: 'Nestle India' },
  NTPC:        { sector: 'Energy',          fullName: 'NTPC' },
  ONGC:        { sector: 'Oil & Gas',       fullName: 'ONGC' },
  POWERGRID:   { sector: 'Energy',          fullName: 'Power Grid' },
  RELIANCE:    { sector: 'Oil & Gas',       fullName: 'Reliance Industries' },
  SBILIFE:     { sector: 'Insurance',       fullName: 'SBI Life' },
  SBIN:        { sector: 'Banking',         fullName: 'State Bank of India' },
  SHREECEM:    { sector: 'Manufacturing',   fullName: 'Shree Cement' },
  SUNPHARMA:   { sector: 'Healthcare',      fullName: 'Sun Pharma' },
  TATACONSUM:  { sector: 'Consumer Goods',  fullName: 'Tata Consumer' },
  TATAMOTORS:  { sector: 'Automobile',      fullName: 'Tata Motors' },
  TATASTEEL:   { sector: 'Metals',          fullName: 'Tata Steel' },
  TCS:         { sector: 'IT',              fullName: 'TCS' },
  TECHM:       { sector: 'IT',              fullName: 'Tech Mahindra' },
  TITAN:       { sector: 'Consumer Goods',  fullName: 'Titan' },
  ULTRACEMCO:  { sector: 'Manufacturing',   fullName: 'UltraTech Cement' },
  WIPRO:       { sector: 'IT',              fullName: 'Wipro' },
};

module.exports = sectorMap;